#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt, but don't fail, to set APP_HOME
APP_HOME=$(cd -P -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd -P || printf '%s\n' "$0")

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

# Location of the system's char set, if available
if [ -n "$LC_ALL" ]; then
  if [ -x "$LC_ALL" ]; then
    export LC_ALL
  fi
fi

# Ensure the Gradle wrapper JAR exists
if [ ! -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
  echo "ERROR: gradle-wrapper.jar not found in $APP_HOME/gradle/wrapper/"
  echo "Please run: gradle wrapper --gradle-version 8.5"
  exit 1
fi

exec java -Xmx64m -Xms64m -Dorg.gradle.appname="$APP_NAME" \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain "$@"